#!/bin/bash

duplicated_domain="$(mktemp)"

for domain in $(cat inactive list | grep -Ev '^(#|$)' | sort | uniq -c | grep -Ev '^\s+1' | awk '{print $NF}'); do
    echo "$domain" >> "$duplicated_domain"
done

if [ "$(wc -l < "$duplicated_domain")" -gt "0" ]; then
    echo "Duplicated domain(s):" 1>&2
    for domain in $(cat "$duplicated_domain"); do
        echo "$domain in: $(grep -E "^${domain}$" inactive list | sort | uniq | awk -F':' '{print $1}' | xargs)" 1>&2
    done
    rm "$duplicated_domain"
    exit 1
else
    ACTIVE_COUNT="$(grep -Ecv '^(#|$)' list)"
    INACTIVE_COUNT="$(grep -Ecv '^(#|$)' inactive)"
    echo "No duplicated domain detected, $((ACTIVE_COUNT+INACTIVE_COUNT)) domains in total, $INACTIVE_COUNT inactive, $ACTIVE_COUNT active."
fi

rm "$duplicated_domain"
